### ISSUE TITLE
BFI

### ISSUE THREAD

**Issue by BintongZhao** [kfoysalhaque/Wi-BFI#1]
Hello, when can you open source your BFI extraction tool, I am very interested in this, thank you

**Comment by kfoysalhaque** [comment]
Hi!  thank you so much for your interest. We will present our work in WiNTECH 2023, on October 06.  A couple of weeks after that (at the latest), it will be available.

**Comment by kfoysalhaque** [comment]
Hello @Flaselord  ,  Wi-BFI has been open-sourced already. Thanks for your interest.
