### ISSUE TITLE
Device Recommendation

### ISSUE THREAD

**Issue by yiliren** [kfoysalhaque/Wi-BFI#2]
I understand BFI could be extracted from many NICs and devices. 

But I would like to know what brand and model of router and laptop are most suitable for BFI-related research. 

Do you have any recommendations? 

Thanks.

**Comment by kfoysalhaque** [comment]
@yiliren 
Actually, for setting up the network, you can use any router as AP and a laptop or other device as a client. However, for the capturing device (where Wi-BFI is installed) we have noticed that you need to switch to monitor mode for the traces to have the Beamforming Feedback Angles. 

Thus, all the NICs that allow being switched to monitor mode with tools like airmon-ng are fine. We have tested Intel AX200, and AX210 for extracting IEEE 802.11ax and IEEE 802.11ac BFI and Intel 8265 for 11ac with Ubuntu 20.04 and 22.04. 

For clients, you can also use AX200 and for AP Asus AX86u is not a bad choice. But any router with OpenWrt installed or that allows installing OpenWrt is a better choice.

**Comment by yiliren** [comment]
Thanks for your reply.

Can I use Wi-BFI to extract BFI between an 802.11n AP and an 802.11n client?

Or, both the router and the AP have to be 802.11ax/ac devices?

Thanks.

**Comment by kfoysalhaque** [comment]
Unfortunately, It does not support 802.11n the way it is. As you know, 11n  NDP and BFI frame structure is a little bit different from  11ac / 11ax. However, with very little change you can adapt Wi-BFI for 11n as well. But that will only let you collect SU-MIMO BFI. But please make sure, the routers that you are using support explicit beamforming.  As far as I know, unfortunately, not all the vendors implemented explicit beamforming. 

If you have any 11n traces with known configurations, I can have a look when I have some time.

**Comment by yiliren** [comment]
Got it. Thanks!

**Comment by yiliren** [comment]
Hi,

I have another question about the device.

I noticed that in your paper, BeamSense: Rethinking Wireless Sensing with MU-MIMO Wi-Fi Beamforming Feedback, both the AP and the STAs are implemented through Netgear Nighthawk X4S AC2600 routers.

Do these routers install OpenWrt? Can you share more information about how to implement that?

Thanks!

**Comment by kfoysalhaque** [comment]
Hello, 

yes, I installed OpenWrt in the mentioned Netgear routers. To be specific, I installed  **openwrt-22.03.2_r7800-squashfs** image through  **TFTP flashing**. This allowed us to implement different network configurations like  **4x2, 3x2, and 2x2** both with **SU-MIMO** and **MU-MIMO**

**Comment by yiliren** [comment]
Got it. Thank you!
