### ISSUE TITLE
Code running error

### ISSUE THREAD

**Issue by DaoChenLiu** [kfoysalhaque/Wi-BFI#3]
Hello,  I tried to run script about real-time plot from live capture, but met a error, which said NameError: name order_angles is not defined.  Could you give me some advice?
![image-20231116181135036](https://cdn.jsdelivr.net/gh/DaoChenLiu/image2/img12/202311161811653.png)

**Comment by kfoysalhaque** [comment]
Hello, thanks for letting me know. There was a bug in the real-time plot script. I have fixed the bug and tested both the functionalities -- BFAs extraction & Vmatrix reconstruction **and** real-time plotting. Please pull the latest commits and it should be fixed. 

A couple of points for the live plotting, you might need to install the conda environment as instructed in the README. On top of that please install texlive-full, PySimpleGUI, cairocffi, and nest-asyncio.

Thanks.
