### ISSUE TITLE
some questions of my data

### ISSUE THREAD

**Issue by Xloading-919** [kfoysalhaque/Wi-BFI#5]
Hello, I am a beginner in WiFi. I would like to know if the packets captured using live capture do not have a file extension. Do I need to manually add a file extension before using the `main.py` script for parsing and processing?

Also, does the following error mean that the data I captured is empty?
![2024-10-09_11-16](https://github.com/user-attachments/assets/90a69c5d-7fd7-49e3-8b35-34e2eea6be70)

**Comment by kfoysalhaque** [comment]
Hi, to capture traces with tools like tcpdump, you need to manually add the appropriate file extension. Wireshark is also a good option, and you can apply display filters like ```wlan.vht.mimo_control.feedbacktype==SU``` to confirm if you're capturing beamforming feedback packets. When saving the capture, use the ```.pcap``` or ```.pcapng``` extension so it can be processed later by the main.py script.

Note 1: main.py doesn't support live capture; for that, use main_live_plot.py. However, it's generally better to start with pre-captured traces to ensure that beamforming feedback is accurately captured.

Note 2: Remember to switch to monitor mode before starting a capture with tcpdump or Wireshark.

**Comment by Xloading-919** [comment]
Hello, I am currently using the `angle_collection.sh` script provided in the project to capture packets. I can see the packet contents in Wireshark, but when I follow the example to run the `main.py` script, I am unable to get the parsed results. Do you have any suggestions or insights regarding this issue?

wireshark: 
![2024-10-09_16-24](https://github.com/user-attachments/assets/ae63fdf3-a168-4596-a208-d477ccc0b13f)
![2024-10-09_16-30](https://github.com/user-attachments/assets/08eaad8d-bb1e-48cd-b405-eb5d99731619)

Error：
![2024-10-09_16-34](https://github.com/user-attachments/assets/ad947096-9e86-43f5-8d70-4472bf0a6673)

**Comment by kfoysalhaque** [comment]
The screenshot you provided doesn't fully demonstrate that you're capturing the feedback. While I can see that those are VHT packets with the correct destination, could you please apply the display filter I suggested earlier and let me know how many filtered packets you're able to capture?

Are you able to observe the phi and psi values in the filtered packets?

Could you confirm whether you're able to extract the angles from the example traces provided in the repository? Additionally, when you capture packets using tcpdump/Wireshark, are you able to extract these values offline, as I suggested?

The live demo is best suited for situations when you're confident that everything in your system is functioning as expected.

It seems you're not capturing any feedback packets. As I mentioned before, it's always a good idea to start with the pre-captured traces.
